version: '3.8'

services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:latest
    container_name: kokoro-tts
    ports:
      - "8880:8880"
    volumes:
      - kokoro-models:/app/models
    environment:
      - MODEL_SIZE=v0_19
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8880/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  kokoro-models:
    driver: local